// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "src/models/schema.prisma",
  migrations: {
    path: "src/models/migrations",
    seed: "ts-node src/models/seed/seeder.ts",
  },
  datasource: {
    url: process.env.DATABASE_URL!,
  },
});
